[package]
name = "qr_video_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbar-rust = "0.0.19"
opencv = "0.64.1"